### ISSUE TITLE
module 'secret' has no attribute 'HOST'

### ISSUE THREAD

**Issue by mrjawright** [jzmiller1/ExchangeConflict2016#1]
Traceback (most recent call last):
  File "wars.py", line 16, in <module>
    r = redis.StrictRedis(host=secret.HOST,
AttributeError: module 'secret' has no attribute 'HOST'

am I missing something?

**Comment by jzmiller1** [comment]
If you want to try to run it you'll need to make a secret.py that has your redis HOST and other information that's not stored in the repository.   There's no redis server up for you to connect to so you'd need to run your own.

**Comment by mrjawright** [comment]
you might want to consider renaming that or creating a class for them in server.py, so that it doesn't conflict with the existing "secret" module that's used for crypto...makes the intent more clear.
