### ISSUE TITLE
Continue project?

### ISSUE THREAD

**Issue by cculver78** [jzmiller1/ExchangeConflict2016#3]
I started writing my own TW python game and I saw yours.  Would you be interested in continuing this project with me?  Here is a screenshot of mine.

<img width="382" alt="Screenshot 2023-06-11 at 12 56 40 PM" src="https://github.com/jzmiller1/ExchangeConflict2016/assets/131779549/f7fe0664-1b6e-42af-a80b-23dfd29bc3f1">

<img width="447" alt="Screenshot 2023-06-11 at 12 57 02 PM" src="https://github.com/jzmiller1/ExchangeConflict2016/assets/131779549/f9b781a4-4b2d-4a1b-a71b-ee7e74435098">

**Comment by jzmiller1** [comment]
Hey!  Your example is looking good!

One reason I kind of let this go is that I could not decide on how people would actually play it?  What did you have in mind for interacting with the game server?

**Comment by cculver78** [comment]
Thank you.  I spent a day or two working on the generation and warping/movement but thats about all I have done.  Please reply to me personally.  I couldn't find any way to reach you other than creating this issue.    I don't want to post my real info here, so its ge2o859@wuuvo.com  That will reach me and I'll get you my real email from there.

**Comment by cculver78** [comment]
Thats one of those "temporary" email things so it expires in 3 hours.

**Comment by cculver78** [comment]
Here is a better, more permanent, email.  Please give me a shout so we can discuss this not in your issues section.  Thanks!

Chuck

github@chuckculver.com
